[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Machillka"

[social.params]
icon = "brand-github"

[[social]]
identifier = "bilibili"
name = "Bilibili"
url = "https://space.bilibili.com/611004244"

[social.params]
icon = "brand-bilibili"

[[social]]
identifier = "email"
name = "E-mail"
url = "mailto:mail@machillka.me"

[social.params]
icon = "brand-gmail"