mainSections = ["post"]
rssFullContent = true
favicon = "/avatar.png"

[sidebar]
description = "A blog on some thinking"

[sidebar.avatar]
enabled = true
local = true
src = "img/avatar.png"

[footer]
since = 1999

[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true